const SET_CURRENT_USER = "SETCURRENTUSER";
const SET_PROFILE = "SETPROFILE"
const UPDATE_HAS_PROFILE = "UPDATEHASPROFILE";
const ERRORS = "ERRORS";
const SET_CAMPAIGN = "SETCAMPAIGN";


export {
    SET_CURRENT_USER,
    ERRORS,
    SET_PROFILE,
    UPDATE_HAS_PROFILE,
    SET_CAMPAIGN
}